language: c
sudo: required
dist: trusty
install:
    - sudo apt-get update
    - sudo apt-get install cmake
    - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
    - tar -xvf cmocka-1.0.1.tar.xz
    - cd cmocka-1.0.1/
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ../
    - make
    - sudo make install
    - cd ../../
    - mkdir build
    - cd build
script: cmake .. && make && ctest -V
